services:
  artifact-server:
    build:
      # docker buildx bake --push
      context: .
      dockerfile: Dockerfile
      tags:
        - davbfr/artifact:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: davbfr/artifact:latest
    container_name: artifact-server
    volumes:
      - ./data:/var/uploads
    environment:
      - ART_API_TOKEN
      - ART_MAX_FILE_SIZE
    restart: unless-stopped
    ports:
      - "9080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./server
          ignore:
            - server/tmp/
        - action: rebuild
          path: ./web
          ignore:
            - web/.dart_tool/
            - web/build/
        - action: rebuild
          path: ./Dockerfile
